SocNetwork_/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SocNetwork_.Data;
using SocNetwork_.Models;
using SocNetwork_.Service;
using SocNetwork_.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SocNetwork_.Controllers
{
    public class ChatController : Controller
    {
        private readonly ILogger<ChatController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ServiceLogic _serviceLogic;
        public ChatController(ServiceLogic serviceLogic,ILogger<ChatController> logger, UserManager<ApplicationUser> userManager)
        {
            _serviceLogic = serviceLogic;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;

            if (User.Identity.IsAuthenticated)
                ViewBag.CurrentUserName = user.firstName + " " + user.lastName;

            ChatViewModel model = await _serviceLogic.ChatView(user);
            return View(model);
        }

        public async Task<IActionResult> Create(Message message)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
                message.UserID = user.Id;
                message.UserName = User.Identity.Name;
                message.User = user;
                await _serviceLogic.CreateMessage(message);
                return Ok();
            }
            return Error();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SocNetwork_/Controllers/HomeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocNetwork_.Data;
using SocNetwork_.ModelDto;
using SocNetwork_.Models;
using SocNetwork_.Service;
using SocNetwork_.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SocNetwork_.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ServiceLogic _serviceLogic;

        public HomeController(ServiceLogic ServiceLogic, ILogger<HomeController> logger, UserManager<ApplicationUser> userManager)
        {
            _serviceLogic = ServiceLogic;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<ActionResult> Index(string textForPost, IFormFile postFile)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
                if (textForPost != null && postFile != null)
                {
                    await _serviceLogic.CreatePost(textForPost, postFile, user);
                }

                var posts = await _serviceLogic.GetPosts(user, userId);

                return View(posts);
            }
            else
                return View();
        }

        [HttpPost]
        public IActionResult AddNews(IFormFile image)
        {
            ApplicationUser tbl_News = new ApplicationUser();
            if (image != null)
            {

                //Set Key Name
                string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(image.FileName);

                //Get url To Save
                string SavePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", ImageName);

                using (var stream = new FileStream(SavePath, FileMode.Create))
                {
                    image.CopyTo(stream);
                }
            }
            return View();
        }

        public async Task<IActionResult> Photos()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            user.UserPictures = await _serviceLogic.GetPhotos(userId);

            return View(user);
        }

        [HttpPost]
        public async Task<JsonResult> AddLike(int id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var postSrv = await _serviceLogic.AddLike(userId, id);

            return Json(postSrv.LikedUsers.Count);
        }

        [HttpPost]
        public async Task<JsonResult> AddComment(int id, string comment)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            CommentDto responseData = await _serviceLogic.AddComment(userId, id, comment);
            return Json(responseData);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SocNetwork_/Controllers/SearchController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SocNetwork_.Data;
using SocNetwork_.Models;
using SocNetwork_.Service;
using SocNetwork_.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocNetwork_.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger<SearchController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ServiceLogic _serviceLogic;

        public SearchController(ServiceLogic serviceLogic, ILogger<SearchController> logger, UserManager<ApplicationUser> userManager)
        {
            _serviceLogic = serviceLogic;
            _userManager = userManager;
            _logger = logger;
        }

        // GET: SearchController
        public async Task<ActionResult> Index()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            var model = await _serviceLogic.SearchIndex(user);
            return View(model);
        }

        public async Task<IActionResult> Search(string userInputName)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            SearchPageViewModel model = await _serviceLogic.SearchUser(user, userInputName);
            return View("Index", model);
        }

        public async Task<IActionResult> AddFriend(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            ApplicationUser userTo = _userManager.FindByIdAsync(id).Result;
            await _serviceLogic.SearchUserAddFriend(user, userTo);
            return LocalRedirect("~/Search"); ;
        }

        public async Task<IActionResult> Accept(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            ApplicationUser friendUser = _userManager.FindByIdAsync(id).Result;
            await _serviceLogic.AcceptFreindRequest(friendUser, user, id, userId);
            return LocalRedirect("~/Search"); ;
        }

        public async Task<IActionResult> Decline(string id)
        {
            await _serviceLogic.DeclineFreindRequest(id);
            return View();
        }

        public async Task<IActionResult> UserViewPage(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            ApplicationUser userView = _userManager.FindByIdAsync(id).Result;
            var model = await _serviceLogic.UserView(userView, user, id);
            return View(model);
        }

        // GET: SearchController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public JsonResult GetSearchingData(string SearchBy, string SearchValue)
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            if (SearchBy == "ID")
            {
                try
                {
                    string id = SearchValue;
                    users = _userManager.Users.Where(x => x.Id == id || SearchValue == null).ToList();
                }
                catch (FormatException)
                {
                    Console.WriteLine("(0) is not A ID", SearchValue);
                }
                return Json(users, new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                users = _userManager.Users.Where(x => x.firstName.Contains(SearchValue) || SearchValue == null).ToList();
                return Json(users, new Newtonsoft.Json.JsonSerializerSettings());
            }
        }

        // GET: SearchController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SearchController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SearchController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SearchController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SearchController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SearchController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SocNetwork_/Views/Home/Index.cshtml
@model SocNetwork_.ViewModels.PostViewModel
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style>
    .panel-shadow {
        box-shadow: rgba(0, 0, 0, 0.3) 7px 7px 7px;
    }

    .panel-white {
        border: 1px solid #dddddd;
    }

        .panel-white .panel-heading {
            color: #333;
            background-color: #fff;
            border-color: #ddd;
        }

        .panel-white .panel-footer {
            background-color: #fff;
            border-color: #ddd;
        }

    .post .post-heading {
        height: 95px;
        padding: 20px 15px;
    }

        .post .post-heading .avatar {
            width: 60px;
            height: 60px;
            display: block;
            margin-right: 15px;
        }

        .post .post-heading .meta .title {
            margin-bottom: 0;
        }

            .post .post-heading .meta .title a {
                color: black;
            }

                .post .post-heading .meta .title a:hover {
                    color: #aaaaaa;
                }

        .post .post-heading .meta .time {
            margin-top: 8px;
            margin-left: 100px;
            color: #999;
        }

    .post .post-image .image {
        width: 100%;
        height: auto;
    }

    .post .post-description {
        padding: 15px;
    }

        .post .post-description p {
            font-size: 14px;
        }

        .post .post-description .stats {
            margin-top: 20px;
        }

            .post .post-description .stats .stat-item {
                display: inline-block;
                margin-right: 15px;
            }

                .post .post-description .stats .stat-item .icon {
                    margin-right: 8px;
                }

    .post .post-footer {
        border-top: 1px solid #ddd;
        padding: 15px;
    }

        .post .post-footer .input-group-addon a {
            color: #454545;
        }

        .post .post-footer .comments-list {
            padding: 0;
            margin-top: 20px;
            list-style-type: none;
        }

            .post .post-footer .comments-list .comment {
                display: block;
                width: 100%;
                margin: 20px 0;
            }

                .post .post-footer .comments-list .comment .avatar {
                    width: 35px;
                    height: 35px;
                }

                .post .post-footer .comments-list .comment .comment-heading {
                    display: block;
                    width: 100%;
                }

                    .post .post-footer .comments-list .comment .comment-heading .user {
                        font-size: 14px;
                        font-weight: bold;
                        display: inline;
                        margin-top: 0;
                        margin-right: 10px;
                    }

                    .post .post-footer .comments-list .comment .comment-heading .time {
                        font-size: 12px;
                        color: #aaa;
                        margin-top: 0;
                        display: inline;
                    }

                .post .post-footer .comments-list .comment .comment-body {
                    margin-left: 50px;
                }

                .post .post-footer .comments-list .comment > .comments-list {
                    margin-left: 50px;
                }
</style>
@if (User.Identity.IsAuthenticated == false)
{
    <div class="text-left">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>
}
@if (User.Identity.IsAuthenticated)
{

    <div class="container text-center">
        <div class="row">
            <div class="col-sm-3 well">
                <div class="well">
                    <p>
                        <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">My Profile</a>
                    </p>
                    <img src="data:image/png;base64, @Model.profilePicture" class="img-circle" height="65" width="65" alt="Avatar">
                    <h5> <a style="color:blue" href='@Url.Action("UserViewPage", "Search", new {id=Model.id })'> @Model.firstName @Model.lastName </a> </h5>
                </div>
                <p><a asp-controller="Home" asp-action="Photos">Photos</a></p>
                <p><a asp-controller="Chat" asp-action="index1">chat</a></p>
                <p><a href="#">Link</a></p>
            </div> 
            <div class="col-sm-7">
                <div class="row">
                    <div class="col-sm-12">

                        <form class="col-xs-12" method="post" action="/Home/Index" enctype="multipart/form-data">

                            <input class="form-control" type="text" name="textForPost" placeholder="What's on your mind?">

                            <div class="form-group">
                                <input type="file" class="form-control" name="postFile" />
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary col-xs-12">Add</button>
                            </div>
                        </form>

                    </div>
                </div>
                <div class="row">

                    @foreach (var item in Model.post)
                    {
                        <div class="container bootstrap snippets bootdey">
                            <div class="col-sm-12">
                                <div class="panel panel-white post panel-shadow">
                                    <div class="post-heading">
                                        <div class="pull-left image">
                                            <img src="data:image/png;base64, @item.ApplicationUser.ProfilePicture" class="img-circle avatar" alt="user profile image">
                                        </div>
                                        <div class="pull-left meta">
                                            <div class="title h5">
                                                <h5> <a style="color:blue" href='@Url.Action("UserViewPage", "Search", new {id=@item.ApplicationUser.Id })'> @item.ApplicationUser.firstName @item.ApplicationUser.lastName </a> </h5>
                                            </div>
                                            <h6 class="text-muted time">@item.dateTimePost</h6>
                                        </div>
                                    </div>
                                    <div class="post-image">
                                        <img src="data:image/png;base64, @item.Picture" class="image" alt="image post">
                                    </div>
                                    <div class="post-description">
                                        <h4>Foto title</h4>
                                        <p>@item.textForPicture</p>
                                        <div class="stats">
                                            <button onclick="AddLike(@item.id)" class="btn btn-default stat-item">
                                                <i id="@item.id" class="fa fa-thumbs-up icon">
                                                    @if (item.LikedUsers.Count > 0)
                                                    {
                                                        @item.LikedUsers.Count
                                                    }
                                                </i>
                                            </button>
                                        </div>
                                    </div>
                                    <div id="PostFooter" class="post-footer">

                                        @*<form class="input-group">
                                            <input asp-for="@item.id" name="id" id="id" hidden />
                                            <input value="@System.IO.Path.GetFileNameWithoutExtension(ViewContext.View.Path)" name="PageName" hidden />
                                            </form>*@
                                        <div style="display:inline-block">
                                            <input style="width:525px" class="form-control" id="inputComment" placeholder="Add a comment" type="text">
                                        </div>
                                        <button onclick="AddComment(@item.id)" style="float:right " @*asp-action="AddComment"*@ class="btn btn-outline-secondary" type="submit"><i class="fa fa-edit"></i></button>

                                        <ul id="@item.id" class="comments-list">
                                            @foreach (var item2 in item.CommentingUsers)
                                            {
                                                <li class="comment">
                                                    <a class="pull-left" href='@Url.Action("UserViewPage", "Search", new {id=item2.CommentingUserId })'>
                                                        <img class="avatar" src="data:image/png;base64,@item2.CommentingUser.ProfilePicture" alt="avatar">
                                                    </a>
                                                    <div class="comment-body">
                                                        <div class="comment-heading">
                                                            <h4 class="user">@item2.CommentingUser.firstName @item2.CommentingUser.lastName</h4>
                                                            <h5 class="time">@item2.DateTime</h5>
                                                        </div>
                                                        <p>@item2.Comment</p>
                                                    </div>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="col-sm-2 well">
                <div class="thumbnail">
                    <p>Upcoming Events:</p>
                    <img src="https://www.voyagesdereve.ch/upload/images/Paris-Tour-Eiffel.jpg" alt="Paris" width="400" height="300">
                    <p><strong>Paris</strong></p>
                    <p>Fri. 27 November 2015</p>
                    <button class="btn btn-primary">Info</button>
                </div>
                <div class="well">
                    <p>ADS</p>
                </div>
                <div class="well">
                    <p>ADS</p>
                </div>
            </div>
        </div>
    </div>
}
@*$("#myimage").attr("src","data:image/jpg;base64," + "Qk02EA4AAA....")*@
<script src="~/js/site.js"></script>