SocNetwork_/Controllers/FriendController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocNetwork_.Data;
using SocNetwork_.Models;
using SocNetwork_.Service;
using SocNetwork_.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocNetwork_.Controllers
{
    public class FriendController : Controller
    {
        private readonly ILogger<FriendController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ServiceLogic _serviceLogic;

        public FriendController(ServiceLogic serviceLogic, ILogger<FriendController> logger, UserManager<ApplicationUser> userManager)
        {
            _serviceLogic = serviceLogic;
            _userManager = userManager;
            _logger = logger;
        }
        // GET: FriendController
        public async Task<ActionResult> Index()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            FriendsViewModel model = await _serviceLogic.GetFriends(user);
            return View(model);
        }

        public async Task<IActionResult> Search(string userInputName)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            FriendsViewModel model = await _serviceLogic.SearchFriend(user, userInputName);
            return View("Index", model);
        }

        public async Task<ActionResult> DeleteFriend(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            ApplicationUser friendUser = _userManager.FindByIdAsync(id).Result;
            await _serviceLogic.DeleteFriend(user, userId, friendUser, id);
            return RedirectToAction("Index");
        }

        // GET: FriendController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FriendController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FriendController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FriendController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FriendController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FriendController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FriendController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SocNetwork_/Controllers/SearchController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SocNetwork_.Data;
using SocNetwork_.Models;
using SocNetwork_.Service;
using SocNetwork_.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocNetwork_.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger<SearchController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ServiceLogic _serviceLogic;

        public SearchController(ServiceLogic serviceLogic, ILogger<SearchController> logger, UserManager<ApplicationUser> userManager)
        {
            _serviceLogic = serviceLogic;
            _userManager = userManager;
            _logger = logger;
        }

        // GET: SearchController
        public async Task<ActionResult> Index()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            var model = await _serviceLogic.SearchIndex(user);
            return View(model);
        }

        public async Task<IActionResult> Search(string userInputName)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            SearchPageViewModel model = await _serviceLogic.SearchUser(user, userInputName);
            return View("Index", model);
        }

        public async Task<IActionResult> AddFriend(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            ApplicationUser userTo = _userManager.FindByIdAsync(id).Result;
            await _serviceLogic.SearchUserAddFriend(user, userTo);
            return LocalRedirect("~/Search"); ;
        }

        public async Task<IActionResult> Accept(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            ApplicationUser friendUser = _userManager.FindByIdAsync(id).Result;
            await _serviceLogic.AcceptFreindRequest(friendUser, user, id, userId);
            return LocalRedirect("~/Search"); ;
        }

        public async Task<IActionResult> Decline(string id)
        {
            await _serviceLogic.DeclineFreindRequest(id);
            return View();
        }

        public async Task<IActionResult> UserViewPage(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            ApplicationUser userView = _userManager.FindByIdAsync(id).Result;
            var model = await _serviceLogic.UserView(userView, user, id);
            return View(model);
        }

        // GET: SearchController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public JsonResult GetSearchingData(string SearchBy, string SearchValue)
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            if (SearchBy == "ID")
            {
                try
                {
                    string id = SearchValue;
                    users = _userManager.Users.Where(x => x.Id == id || SearchValue == null).ToList();
                }
                catch (FormatException)
                {
                    Console.WriteLine("(0) is not A ID", SearchValue);
                }
                return Json(users, new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                users = _userManager.Users.Where(x => x.firstName.Contains(SearchValue) || SearchValue == null).ToList();
                return Json(users, new Newtonsoft.Json.JsonSerializerSettings());
            }
        }

        // GET: SearchController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SearchController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SearchController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SearchController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SearchController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SearchController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SocNetwork_/Views/Search/Index.cshtml
@model SocNetwork_.ViewModels.SearchPageViewModel
@{ ViewData["Title"] = "Index"; }

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    body {
        font-family: Arial;
    }

    * {
        box-sizing: border-box;
    }

    form.example input[type=text] {
        padding: 10px;
        font-size: 17px;
        border: 1px solid grey;
        float: left;
        width: 80%;
        background: #f1f1f1;
    }

    form.example button {
        float: left;
        width: 20%;
        padding: 10px;
        background: #2196F3;
        color: white;
        font-size: 17px;
        border: 1px solid grey;
        border-left: none;
        cursor: pointer;
    }

        form.example button:hover {
            background: #0b7dda;
        }

    form.example::after {
        content: "";
        clear: both;
        display: table;
    }
</style>
<style>
    body {
        margin-top: 20px;
        background: #FAFAFA;
    }
    /*==================================================
    Nearby People CSS
    ==================================================*/

    .people-nearby .google-maps {
        background: #f8f8f8;
        border-radius: 4px;
        border: 1px solid #f1f2f2;
        padding: 20px;
        margin-bottom: 20px;
    }

        .people-nearby .google-maps .map {
            height: 300px;
            width: 100%;
            border: none;
        }

    .people-nearby .nearby-user {
        padding: 20px 0;
        border-top: 1px solid #f1f2f2;
        border-bottom: 1px solid #f1f2f2;
        margin-bottom: 20px;
    }

    img.profile-photo-lg {
        height: 80px;
        width: 80px;
        border-radius: 50%;
    }
</style>
<div class="container text-center">
    <div class="row">
        <div class="col-sm-3 well">
            <div class="well">
                @if (Model.FriendsRequest != null)
                {
    @foreach (var item in Model.FriendsRequest)
    {
<h3>Friend Request</h3>
                    <div class="w3-container w3-center">

                        <img src="data:image/png;base64,@item.friendFrom.ProfilePicture" alt="Avatar" style="width:80%">
                        <h5><a style="color:blue" href='@Url.Action("UserViewPage", "Search", new {id=@item.friendFromId })'> @item.friendFrom.firstName @item.friendFrom.lastName </a> </h5>
                        <h6>@item.RequestTime</h6>
                        <div class="w3-section">
                            <input type="button" value="Accept" onclick="location.href='@Url.Action("Accept", "Search", new { id = @item.friendFrom.Id })'" />
                            <input type="button" value="Decline" onclick="location.href='@Url.Action("Decline", "Search", new { id = @item.friendFrom.Id })'" />
                        </div>
                    </div>}}
                @if (Model.FriendsRequest.Count == 0)
                {
    <h3>Friendship requests will be shown here</h3>}
            </div>
        </div>

        <div class="col-sm-7">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default text-left">
                        <div class="panel-body">
                            <form class="example">
                                <input type="text" placeholder="Search.." name="UserInputName" id="UserInputName">
                                <button asp-action="Search" type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @if (Model != null)
            {
@foreach (var item in Model.Users)
{
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="people-nearby">
                <div class="nearby-user">
                    <div class="row">
                        <div class="col-md-2 col-sm-2">
                            <img src="data:image/png;base64, @item.ProfilePicture" alt="Red dot" class="profile-photo-lg">
                        </div>
                        <div class="col-md-7 col-sm-7">
                            <h5> <a style="color:blue" href='@Url.Action("UserViewPage", "Search", new {id=@item.Id })'>@item.firstName @item.lastName </a> </h5>
                            <p>Software Engineer</p>
                        </div>
                        <div class="col-md-3 col-sm-3">
                            @if (Model.UserFriends.Count != 0)
                            {
                                 @foreach (var friend in Model.UserFriends)
                                 {
                                 @if (item.Id == friend.userId)
                                 {
                                 <input type="button" value="Delete" onclick="location.href='@Url.Action("DeleteFriend", "Friend", new { id = @item.Id })'" /> }
                                                             else
                                                             {
                                 <input type="button" value="Add Friend" onclick="location.href='@Url.Action("AddFriend", "Search", new { id = @item.Id })'" />}}}
                            else
                            {
                                <input type="button" value="Add Friend" onclick="location.href='@Url.Action("AddFriend", "Search", new { id = @item.Id })'" />
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 }
}
        </div>
    </div>
</div>